const version = require('../package.json').version

export const NEXUS_GRAPHQL_HEADER = `\
/**
 * This file was automatically generated by nexus-graphql@${version}
 * Do not make changes to this file directly
 */`

export const TYPE_NAMESPACE = 'types';
