const version = require('../package.json').version

export const NEXUS_GRAPHQL_HEADER = `\
/**
 * This file was automatically generated by nexus-graphql@${version}
 * Do not make changes to this file directly
 */`

export const IMPORT_TYPE_NAMESPACE = 'types';

export const NAMESPACE = 'NexusWrapperTypes';
export const NAMESPACE_GLOBAL = 'NexusWrapperGen';
